# Generated by Django 2.1.1 on 2018-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingjia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('lasttime', models.DateTimeField(verbose_name='最后登录时间')),
                ('lastip', models.CharField(max_length=20, verbose_name='最后登录ip')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
