# Generated by Django 2.1.1 on 2018-09-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qingjia', '0005_delete_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='record1',
            new_name='record',
        ),
    ]
