# Generated by Django 2.0.7 on 2018-10-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingjia', '0006_auto_20180914_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='why',
            field=models.TextField(verbose_name='原因'),
        ),
    ]
