# Generated by Django 2.1.2 on 2018-10-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qingjia', '0007_auto_20181016_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
