# Generated by Django 2.0.7 on 2018-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('schoolNum', models.CharField(max_length=12, verbose_name='学号')),
                ('grade', models.CharField(max_length=10, verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='sign1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('schoolNum', models.CharField(max_length=12, verbose_name='学号')),
                ('grade', models.CharField(max_length=10, verbose_name='班级')),
                ('group', models.CharField(max_length=100, verbose_name='组别')),
                ('time', models.DateTimeField(max_length=100, verbose_name='签到时间')),
            ],
        ),
    ]
