# Generated by Django 2.0.7 on 2018-08-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0004_lists_sign1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lists',
        ),
        migrations.DeleteModel(
            name='sign1',
        ),
    ]
